### PR TITLE
simple convert to OOP

### PR DESCRIPTION
**Pull request by thgs**
heres my attempt

### CODE REVIEW

**Comment by thgs** [comment]
however i wouldn't like it to merge before @dangenendt PR, as he said he is working on it and I had notified nobody so..

**Comment by dangenendt** [comment]
@thgs 
Your simple approach is absolutely fine.
The only thing what seems a little werid to me is the name of "index2.php" :nerd_face: 
I didnt tested it yet (at work right now), but if its working we can merge that.

**Comment by alexandermarston** [comment]
@dangenendt waiting on your PR before any merge.

**Comment by dangenendt** [comment]
No no no. You can merge it. I just started with bringing in composer and some other smaller stuff. Didnt touched the "old codebase" yet.
Means, when you merge it i could build some further refactorings upon  this branch here :+1:

**Comment by thgs** [comment]
Cant merge it yet. My bad. 
I pulled upstream to resolve conflicts and seems also I forgot to require helpers.php. I think I would like to separate VNStat completely and create a View class to resolve that ugly index2.php
@dangenendt @alexandermarston

**Comment by thgs** [comment]
Now its good to go, I think.

**Review by dangenendt — APPROVED** [review]

**Comment by alexandermarston** [comment]
This PR has been superseeded and is no longer required.

Thanks for the contribution, if you have anything else please raise another PR!

**Pull request closed without merging**
