### PR TITLE
Some refactoring

### PR DESCRIPTION
**Pull request by lonesta**
Added a function to print a table
Auto reformat code with PSR

### CODE REVIEW

**Comment by alexandermarston** [comment]
@lonesta 

It looks like the standards here aren't consistent. In some functions the curly brace is on the same line as the function, in others it's on the line below.

```
function print_options()
{
```

vs

```
function print_options() {
```

**Comment by lonesta** [comment]
@alexandermarston 

Oh, my IDE does not know how to reformat in the HTML sections.
I'll fix it now.

**Comment by alexandermarston** [comment]
@lonesta I still think this is missing some consistency here.

For functions, you are adding the curly brace below the line but for if statements they are on the same line - we should stick with one approach.

**Comment by lonesta** [comment]
@alexandermarston 

I adhere to the standards [PSR-1](https://www.php-fig.org/psr/psr-1/) and [PSR-2](https://www.php-fig.org/psr/psr-2/)

**Pull request merged**
