### PR TITLE
fixed

### PR DESCRIPTION
**Pull request by cremesk**
Compare:
[Refactor vnstat #22](https://github.com/alexandermarston/vnstat-dashboard/pull/22/files)
and
[Fixed infinite loop #24](https://github.com/alexandermarston/vnstat-dashboard/pull/24/files)

### CODE REVIEW

**Comment by alexandermarston** [comment]
@cremesk can you please rebase your branch with the latest changes. Thanks

**Comment by cremesk** [comment]
okay is fixed.

**Comment by alexandermarston** [comment]
@cremesk you should avoid using shell_exec where you don't have to.

Alternatively, to get a hostname you could use gethostname / php_uname

http://php.net/manual/en/function.gethostname.php

**Comment by cremesk** [comment]
preview: https://vpn13.freifunk-dresden.de/vnstat/

**Comment by cremesk** [comment]
@alexandermarston can you pls merge my Pull-Request? :)

**Comment by alexandermarston** [comment]
@cremesk In the code it appears you are generating a graph for the Top 10 days, but I cannot see that being used anywhere.

In addition, on your site I cannot see the Top 10 table being populated either.

**Comment by cremesk** [comment]
@AllanKlaus you have a Solution?

**Comment by AllanKlaus** [comment]
No idea, need to debug better. Looking superficially it apper that the error is in the function `kbytesToString`. But it could not be.

**Comment by cremesk** [comment]
**outdated**

**Pull request closed without merging**
